permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Chaotic Planets"
id : "93214000299"
description : "Build your own chaotic planetary system."
thumb: "thumb.gif"
version: "0.0.2"

ml_url: "http://minutelabs.io"
ml_library: "http://labs.minutelabs.io/library"
ml_assets: "http://labs.minutelabs.io/assets"
library_path: "library"

show :
  branding: true
  details: true
  comments: true
